"""III SDK for Python."""

from iii_observability import (
    DEFAULT_ALLOWLIST,
    REDACTED_PLACEHOLDER,
    BaggageSpanProcessor,
    OtelConfig,
    ReconnectionConfig,
    current_span_id,
    current_span_is_recording,
    current_trace_id,
    execute_traced_request,
    extract_baggage,
    extract_traceparent,
    flush_otel,
    init_otel,
    inject_baggage,
    inject_traceparent,
    record_span_event,
    redact,
    redact_and_truncate,
    resolve_max_bytes_from_env,
    set_current_span_attribute,
    set_current_span_error,
    shutdown_otel,
    with_span,
)

from .channels import ChannelReader, ChannelWriter
from .errors import IIIForbiddenError, IIIInvocationError, IIITimeoutError
from .format_utils import extract_request_format, extract_response_format, python_type_to_format
from .iii import TriggerAction, register_worker
from .iii_constants import FunctionRef, InitOptions, TelemetryOptions
from .iii_types import (
    AuthInput,
    AuthResult,
    EnqueueResult,
    HttpAuthConfig,
    HttpInvocationConfig,
    MessageType,
    MiddlewareFunctionInput,
    OnFunctionRegistrationInput,
    OnFunctionRegistrationResult,
    OnTriggerRegistrationInput,
    OnTriggerRegistrationResult,
    OnTriggerTypeRegistrationInput,
    OnTriggerTypeRegistrationResult,
    RegisterFunctionFormat,
    RegisterFunctionMessage,
    RegisterTriggerInput,
    RegisterTriggerMessage,
    RegisterTriggerTypeInput,
    RegisterTriggerTypeMessage,
    StreamChannelRef,
    TriggerActionEnqueue,
    TriggerActionVoid,
    TriggerRequest,
)
from .stream import (
    IStream,
    StreamChangeEvent,
    StreamChangeEventDetail,
    StreamContext,
    StreamJoinLeaveEvent,
    StreamJoinLeaveTriggerConfig,
    StreamTriggerConfig,
)
from .triggers import Trigger, TriggerConfig, TriggerHandler, TriggerTypeRef
from .types import (
    ApiRequest,
    ApiResponse,
    Channel,
    HttpRequest,
    HttpResponse,
    IIIClient,
    InternalHttpRequest,
    RemoteFunctionHandler,
)
from .utils import http

__all__ = [
    # Telemetry helpers
    "BaggageSpanProcessor",
    "DEFAULT_ALLOWLIST",
    "REDACTED_PLACEHOLDER",
    "current_span_id",
    "current_span_is_recording",
    "current_trace_id",
    "execute_traced_request",
    "extract_baggage",
    "extract_traceparent",
    "flush_otel",
    "init_otel",
    "inject_baggage",
    "inject_traceparent",
    "record_span_event",
    "redact",
    "redact_and_truncate",
    "resolve_max_bytes_from_env",
    "set_current_span_attribute",
    "set_current_span_error",
    "shutdown_otel",
    "with_span",
    # Channels
    "ChannelReader",
    "ChannelWriter",
    # Errors
    "IIIForbiddenError",
    "IIIInvocationError",
    "IIITimeoutError",
    # Core
    "FunctionRef",
    "InitOptions",
    "OtelConfig",
    "ReconnectionConfig",
    "register_worker",
    "TelemetryOptions",
    "TriggerAction",
    # RBAC types
    "AuthInput",
    "AuthResult",
    "MiddlewareFunctionInput",
    "OnFunctionRegistrationInput",
    "OnFunctionRegistrationResult",
    "OnTriggerRegistrationInput",
    "OnTriggerRegistrationResult",
    "OnTriggerTypeRegistrationInput",
    "OnTriggerTypeRegistrationResult",
    # Message types
    "EnqueueResult",
    "HttpAuthConfig",
    "HttpInvocationConfig",
    "MessageType",
    "RegisterFunctionFormat",
    "RegisterFunctionMessage",
    "RegisterTriggerInput",
    "RegisterTriggerMessage",
    "RegisterTriggerTypeInput",
    "RegisterTriggerTypeMessage",
    "StreamChannelRef",
    "TriggerActionEnqueue",
    "TriggerActionVoid",
    "TriggerRequest",
    # Triggers
    "Trigger",
    "TriggerConfig",
    "TriggerHandler",
    "TriggerTypeRef",
    # Types
    "ApiRequest",
    "ApiResponse",
    "Channel",
    "HttpRequest",
    "HttpResponse",
    "IIIClient",
    "InternalHttpRequest",
    "RemoteFunctionHandler",
    # Stream
    "IStream",
    "StreamChangeEvent",
    "StreamChangeEventDetail",
    "StreamContext",
    "StreamJoinLeaveEvent",
    "StreamJoinLeaveTriggerConfig",
    "StreamTriggerConfig",
    # Utilities
    "http",
    # Format extraction
    "extract_request_format",
    "extract_response_format",
    "python_type_to_format",
]
